# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndShoolMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_course', models.CharField(max_length=255, verbose_name='название курса')),
                ('deskr', models.CharField(blank=True, max_length=255, null=True, verbose_name='описание')),
                ('price', models.CharField(blank=True, max_length=50, null=True, verbose_name='цена за курс')),
                ('hours', models.CharField(blank=True, max_length=50, verbose_name='кол-во ак.час')),
            ],
        ),
    ]
