# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-11 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indshool', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indshoolmain',
            options={'verbose_name_plural': 'Индивидуальные Занятия'},
        ),
    ]
