# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-11 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcshool', '0007_auto_20160602_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pcshooldet',
            options={'verbose_name_plural': ''},
        ),
        migrations.AlterModelOptions(
            name='pcshoolmain',
            options={'verbose_name_plural': 'Курсы ПК'},
        ),
        migrations.AlterField(
            model_name='pcshooldet',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coaches.Coach', verbose_name='препод'),
        ),
    ]
