# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designshool', '0004_auto_20160518_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designshool',
            old_name='begin_cours',
            new_name='begin_course',
        ),
        migrations.RenameField(
            model_name='designshool',
            old_name='dates_lesson',
            new_name='day_lesson',
        ),
        migrations.RenameField(
            model_name='designshool',
            old_name='name_cours',
            new_name='name_course',
        ),
        migrations.AlterField(
            model_name='designshool',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coaches.Coach'),
        ),
    ]
