# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designshool', '0006_auto_20160518_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='designshool',
            name='place_course',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='designshool',
            name='sale',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='designshool',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coaches.Coach'),
        ),
        migrations.AlterField(
            model_name='designshool',
            name='name_course',
            field=models.CharField(max_length=255, verbose_name='название курса'),
        ),
    ]
