# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designshool', '0011_auto_20160518_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicedesignshool',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coaches.Coach'),
        ),
        migrations.AlterField(
            model_name='choicedesignshool',
            name='day_lesson',
            field=models.CharField(blank=True, choices=[('mon', 'Пон'), ('tues', 'Вт'), ('wed', 'Ср'), ('thurs', 'Чт'), ('fri', 'Пт'), ('sat', 'Сб'), ('sun', 'Вс')], max_length=2, null=True, verbose_name='дни недели'),
        ),
        migrations.AlterField(
            model_name='choicedesignshool',
            name='time_lesson',
            field=models.CharField(blank=True, choices=[('9:30', '9:30'), ('10:00', '10:00'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('15:00', '15:00'), ('15:30', '15:30'), ('16:00', '16:00'), ('18:00', '18:00'), ('18:30', '18:30')], max_length=5, null=True, verbose_name='время начала занятий'),
        ),
    ]
