# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designshool', '0012_auto_20160518_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='designshool',
            name='choice_detail',
            field=models.ManyToManyField(blank=True, null=True, to='designshool.ChoiceDesignShool'),
        ),
        migrations.AlterField(
            model_name='choicedesignshool',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coaches.Coach'),
        ),
    ]
