# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designshool', '0019_auto_20160525_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designshooldet',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coaches.Coach', verbose_name='препод'),
        ),
        migrations.RemoveField(
            model_name='designshoolmain',
            name='schedule',
        ),
        migrations.AddField(
            model_name='designshoolmain',
            name='schedule',
            field=models.ManyToManyField(blank=True, null=True, to='designshool.DesignShoolDet', verbose_name='график'),
        ),
    ]
