# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LangShoolDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_cours', models.CharField(blank=True, max_length=100, null=True, verbose_name='продолжительность курса')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='цена за курс')),
                ('price_month', models.IntegerField(blank=True, null=True, verbose_name='цена за месяц')),
                ('sale', models.CharField(blank=True, max_length=20, null=True, verbose_name='скидка')),
                ('piple', models.CharField(blank=True, max_length=20, null=True, verbose_name='количество человек')),
                ('regime', models.CharField(blank=True, max_length=30, null=True, verbose_name='режим занятий')),
                ('hours_month', models.CharField(blank=True, max_length=20, null=True, verbose_name='часов в месяц')),
            ],
        ),
        migrations.CreateModel(
            name='LangShoolMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_course', models.CharField(max_length=255, verbose_name='название курса')),
                ('description', models.TextField(blank=True, null=True, verbose_name='развернутое описание')),
                ('titles', models.ManyToManyField(blank=True, to='langshool.LangShoolDet', verbose_name='название и описание')),
            ],
        ),
    ]
